# Generated by Django 4.2.2 on 2023-07-02 13:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('date', models.DateTimeField(default=datetime.datetime(2023, 7, 2, 13, 4, 22, 319781, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
