# Generated by Django 4.2.2 on 2023-07-02 13:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 2, 13, 23, 48, 266084, tzinfo=datetime.timezone.utc)),
        ),
    ]
